accepted = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSD-1-Clause",
    "ISC",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "MIT-0",
    "Unlicense",
]
ignore-dev-dependencies = true
targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
